const books = [
      {
    id: 1,
    title: "The Fellowship of the Ring",
    plot: "The Fellowship of the Ring follows the beginning of an epic quest set in the fantasy world of Middle-earth. Long ago, the Dark Lord Sauron forged the One Ring to control all other Rings of Power. Though he was defeated, the Ring survived, holding the power to corrupt anyone who possesses it. Centuries later, the Ring comes into the hands of the hobbit Frodo Baggins. When the wizard Gandalf discovers its true nature, Frodo is forced to leave his peaceful home in the Shire to keep the Ring from falling into Sauron’s hands. Joined by his loyal friend Sam, and later by Merry and Pippin, Frodo begins a dangerous journey across Middle-earth while being hunted by Sauron’s terrifying Ringwraiths. At the Elven city of Rivendell, a council is held to decide the Ring’s fate. It is revealed that the Ring can only be destroyed in the fires of Mount Doom, deep within Sauron’s realm of Mordor. Frodo volunteers to carry the Ring, and he is joined by eight companions: Aragorn, Gandalf, Legolas, Gimli, Boromir, and his fellow hobbits. Together, they form the Fellowship of the Ring. The Fellowship faces many dangers, including treacherous mountains, ancient evils in the Mines of Moria, and the growing temptation of the Ring itself. After the loss of Gandalf and increasing internal conflict, the Fellowship begins to break apart. Frodo realizes the Ring endangers his companions and decides to continue the quest alone, with Sam choosing to stand by him. The film ends with the Fellowship divided but the journey to destroy the Ring truly underway.",
    date: "2001",
    image: "../public/assets/The-Fellowship-of-the-Ring-Book.webp"
  },
   {
    id: 2,
    title: "The Two Towers",
    plot: "The Two Towers continues the epic journey across Middle-earth as the Fellowship of the Ring is scattered. Frodo Baggins and Samwise Gamgee press on toward Mordor to destroy the One Ring, while their former companions face growing darkness elsewhere. Frodo and Sam are soon joined by Gollum, a twisted creature once corrupted by the Ring. Gollum promises to guide them to Mordor, though his loyalty is uncertain as he struggles between helping Frodo and reclaiming the Ring for himself. As they travel closer to enemy lands, Frodo increasingly feels the weight and corrupting influence of the Ring. Meanwhile, Aragorn, Legolas, and Gimli pursue the Uruk-hai who captured Merry and Pippin. Their chase leads them to the kingdom of Rohan, where they discover that King Théoden has fallen under the influence of the traitorous wizard Saruman. With the help of Gandalf—who returns, transformed and more powerful than before—Théoden is freed from Saruman’s control and prepares his people for war. Merry and Pippin escape captivity and encounter the Ents, ancient tree-like beings who guard the forests. Convincing the Ents that war has come to Middle-earth, they help lead an attack on Saruman’s stronghold of Isengard, severely weakening his power. As Saruman’s armies march on Rohan, Aragorn, Legolas, Gimli, and the Rohirrim make a desperate stand at Helm’s Deep. After a long and brutal battle, Gandalf arrives with reinforcements, turning the tide and securing a hard-won victory. The film ends with Middle-earth on the brink of full-scale war. Frodo and Sam continue their perilous journey toward Mordor, unaware that Gollum’s darker intentions may soon place the quest in grave danger.",
    date: "2002",
    image: "../public/assets/the-two-towers-book.webp"
  },
   {
    id: 3,
    title: "The Return of the King",
    plot: "The Return of the King brings the epic story of Middle-earth to its conclusion as the final struggle against the Dark Lord Sauron begins. With Sauron’s power at its height, the fate of the world rests on a desperate and nearly impossible mission. Frodo Baggins and Samwise Gamgee continue their journey into Mordor, guided by Gollum. As they draw closer to Mount Doom, the Ring’s influence grows stronger, testing Frodo’s strength and will. Gollum’s inner conflict finally turns to betrayal, leading Frodo into danger at Shelob’s lair. Believing Frodo to be dead, Sam briefly carries the Ring before rescuing his friend and continuing the quest. Meanwhile, Aragorn embraces his destiny as the true King of Gondor. Alongside Gandalf, Legolas, Gimli, and the armies of Men, he prepares to face Sauron’s overwhelming forces. Great battles are fought across Middle-earth, including the defense of Minas Tirith against a massive assault from Mordor. Despite heavy losses, the free peoples of Middle-earth refuse to surrender. To give Frodo and Sam a final chance to destroy the Ring, Aragorn leads a last, desperate march to the Black Gate of Mordor, drawing Sauron’s attention away from Mount Doom. Inside the volcanic fires of the mountain, Frodo finally reaches the Cracks of Doom but succumbs to the Ring’s power and refuses to destroy it. In the struggle that follows, Gollum reclaims the Ring but falls into the fire, destroying both himself and the Ring at last. With the Ring destroyed, Sauron’s power collapses and his armies are defeated. Aragorn is crowned King of Gondor, peace returns to Middle-earth, and the Fellowship is reunited. Frodo and his friends return to the Shire forever changed by their journey. In time, Frodo departs Middle-earth for the Undying Lands, bringing the story to a bittersweet and hopeful close.",
    date: "2003",
    image: "../public/assets/the-return-of-the-king-book.jpg"
  }
];

export default books;